### ISSUE TITLE
invalid/impossible solutions

### ISSUE THREAD

**Issue by theapathyimp** [francojreyes/hsr-compass#1]
okay, maybe this is user error (i don't think so, especially since i replicated the problem multiple times), but i've been getting different incorrect/impossible results multiple times after resetting the tool and re-entering the setup.

two invalid solutions, same setup on the tool, and the original puzzle from the game. the solutions are technically identical, and only vary because i did the order slightly different but recorded both for posterity.

![image](https://github.com/francojreyes/hsr-compass/assets/8020193/8d483540-d76d-46e2-a543-383959291c4c)
![image](https://github.com/francojreyes/hsr-compass/assets/8020193/5da14455-4be0-40a8-a739-cb9add6e8baa)
![image](https://github.com/francojreyes/hsr-compass/assets/8020193/e707e51e-f22f-4df8-9198-4eb9f83f5ac3)

**Comment by theapathyimp** [comment]
also, for clarity: i was experiencing a similar issue with a different puzzle setup but wrote it off as a fluke so don't have screenshots of that specific setup.

**Comment by francojreyes** [comment]
I'm not able to replicate this issue. Have you made sure to hit solve? Here's what I get with the setup in your second screenshot (and in the game screenshot, I'm assuming the combinations are the same):

<img width="1394" alt="image" src="https://github.com/francojreyes/hsr-compass/assets/79299724/031ab5a2-3ff7-4720-9f8d-c0087fe870a5">

I think this puzzle is also one of the test cases, specifically Timetable 3-3 [here](https://github.com/francojreyes/hsr-compass/blob/master/src/utils/__tests__/calculateSolution.test.ts) - this is the 3rd puzzle on the 3rd day, right?

**Comment by theapathyimp** [comment]
hmmm, yeah i think you’re right. it does appear to be a match to the test solution you linked, and yes it is puzzle 3 on day 3. i did make sure to click solve, for the record. 

i solved the puzzle on my own the manual way, and tbh i have a lot of firefox extensions and a pretty, let’s say, hodge podge setup on my machine, so i think it’s safe to chalk it up to an issue on my end. 

thanks for the quick testing and response!

next time i’ll use an alternate browser to ensure there’s less interference lol
